pipeline{
    environment {
		registry = 'samnur82/simpleapp'
		registryCred = 'my_dockerhub'
		dockerImage = ''
    }

    agent any

    stages {
        stage('Check Prerequisite') {
            steps {
                sh 'git --version | ant -version | java -version | docker --version'
            }
        }
        stage('clone repo') {
            steps {
               sh 'git pull https://github.com/samnur82/SimpleApp.git docker-dockerfiletest'
            }
        }
        stage('Build Simple Apps War') {
            steps{
	        sh 'ant -Dj2ee.server.home=/opt/tomcat9 -Dlibs.CopyLibs.classpath=/root/nblibrary clean compile'
                sh 'ant -Dj2ee.server.home=/opt/tomcat9 -Dlibs.CopyLibs.classpath=/root/nblibrary dist'
            }
        }	
        stage('Build Simple Apps Docker Images') {
            steps{
	 	script {
                    dockerImage = docker.build registry + ":$BUILD_NUMBER"
		}
            }
        }
        stage('Test Docker Image'){
            steps{
		sh 'docker image ls -a'
            }
	}
        stage('Push Image to Docker Hub'){
            steps{
		script {
                    docker.withRegistry( '', registryCred ) {
			dockerImage.push()

                        dockerImage.push('latest')
                    }
		}	
	    }
	}
    }
}
